name = "FractalHimmelblau"
uuid = "6300030b-4054-496b-b734-038cdb8c89a2"
authors = ["Stephan Scholz"]
version = "0.1.0"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
